version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  security: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  test-deploy:
    jobs:
      - security/scan_dependencies:
          name: scan_dependencies_npm
          pkg_manager: npm
          pkg_json_dir: ~/project/sample
          filters: *filters
      - security/scan_dependencies:
          name: scan_dependencies_pnpm
          pkg_manager: pnpm
          pkg_json_dir: ~/project/sample
          filters: *filters
      - security/scan_dependencies:
          name: scan_dependencies_command
          pkg_manager: npm
          pkg_json_dir: ~/project/sample
          scan_command: |
            #!/bin/bash
            if ! npm audit --audit-level=high; then
              echo "Scan found dependencies with high vulnerability level"
            fi
          filters: *filters
      - security/detect_secrets_dir:
          name: detect_secrets_dir
          filters: *filters
      - security/detect_secrets_git:
          name: detect_secrets_git_base_revision
          base_revision: <<pipeline.git.base_revision>>
          filters: *filters
      - security/detect_secrets_git:
          name: detect_secrets_git_same_revision
          base_branch: <<pipeline.git.branch>>
          base_revision: <<pipeline.git.revision>>
          filters: *filters
      - security/detect_secrets_git:
          name: detect_secrets_git_invalid_revision
          base_branch: <<pipeline.git.branch>>
          base_revision: ec9bf83ad5045208d15f2ec2c0ce4fba8cd7118f
          filters: *filters
      - security/detect_secrets_git:
          name: detect_secrets_git_no_revision
          base_branch: <<pipeline.git.branch>>
          filters: *filters
      - security/analyze_code:
          name: analyze_code_diff
          path: ~/project/sample
          filters: *filters
      - security/analyze_code:
          name: analyze_code_full
          full_scan: true
          rules: p/cwe-top-25
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: studion/security
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - scan_dependencies_npm
            - scan_dependencies_pnpm
            - scan_dependencies_command
            - detect_secrets_dir
            - detect_secrets_git_base_revision
            - analyze_code_diff
            - analyze_code_full
          context: orb-publishing
          filters: *release-filters
